### ISSUE TITLE
Couldn't set the last image as wallpaper

### ISSUE THREAD

**Issue by jeffshee** [BigE/desk-changer#57]
Hi, I'm having issue described above. For testing, I put 3 images file name 1.png, 2.png and 3.png into a folder, then created a profile just to load that folder. When the extension try to set the last image, the error attached below occur.

```
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.490: ::dbus_register
-INFO: 11:53:57.490: successfully registered DBus name /org/gnome/Shell/Extensions/DeskChanger/Daemon
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.492: ::startup
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.493: successfully created DesktopProfile(test)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.493: ::activate
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.493: loading profile test
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.499: adding file:///home/jeffshee/Pictures/Test as directory to watch
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.499: descending into file:///home/jeffshee/Pictures/Test to find wallpapers
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.499: adding wallpaper file:///home/jeffshee/Pictures/Test/1.png
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.499: adding wallpaper file:///home/jeffshee/Pictures/Test/2.png
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.499: adding wallpaper file:///home/jeffshee/Pictures/Test/3.png

(desk-changer-daemon.py:21883): -WARNING **: 11:53:57.500: available wallpapers for test is under 100 (3) - strict random checking is disabled
-INFO: 11:53:57.500: restoring state of profile test
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: no previous state for test
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: DesktopProfile(test)::preview ('file:///home/jeffshee/Pictures/Test/1.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: [DBUS]::preview ('file:///home/jeffshee/Pictures/Test/1.png',)
-INFO: 11:53:57.500: added file:///home/jeffshee/Pictures/Test/1.png to the queue for DesktopProfile(test)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: DesktopProfile(test)::preview ('file:///home/jeffshee/Pictures/Test/2.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: [DBUS]::preview ('file:///home/jeffshee/Pictures/Test/2.png',)
-INFO: 11:53:57.500: added file:///home/jeffshee/Pictures/Test/2.png to the queue for DesktopProfile(test)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: DesktopProfile(test)::changed ('file:///home/jeffshee/Pictures/Test/1.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.500: [DBUS]::changed ('file:///home/jeffshee/Pictures/Test/1.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: successfully loaded test with 3 wallpapers
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: added timer for 300 seconds
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: [DBUS]::Get(history)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: [DBUS]::Get(queue)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: [DBUS]::Get(history)
(desk-changer-daemon.py:21883): -DEBUG: 11:53:57.501: [DBUS]::Get(queue)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:03.727: [DBUS] org.gnome.Shell.Extensions.DeskChanger.Daemon:Next
(desk-changer-daemon.py:21883): -DEBUG: 11:54:03.728: DesktopProfile(test)::preview ('file:///home/jeffshee/Pictures/Test/3.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:03.729: [DBUS]::preview ('file:///home/jeffshee/Pictures/Test/3.png',)
-INFO: 11:54:03.729: added file:///home/jeffshee/Pictures/Test/3.png to the queue for DesktopProfile(test)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:03.730: DesktopProfile(test)::changed ('file:///home/jeffshee/Pictures/Test/2.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:03.730: [DBUS]::changed ('file:///home/jeffshee/Pictures/Test/2.png',)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:07.736: [DBUS] org.gnome.Shell.Extensions.DeskChanger.Daemon:Next
Traceback (most recent call last):
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/application.py", line 335, in _handle_dbus_call
    invocation.return_value(GLib.Variant('(s)', (self.change(),)))
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/application.py", line 74, in change
    wallpaper = getattr(self._desktop_profile, func)()
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/profiles.py", line 275, in next
    wallpaper = self._next(current)
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/profiles.py", line 233, in _next
    self._load_queue(current)
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/profiles.py", line 178, in _load_queue
    self.info('reached end of profile %s, resetting counter to beginning', self)
AttributeError: 'DesktopProfile' object has no attribute 'info'
(desk-changer-daemon.py:21883): -DEBUG: 11:54:19.909: ::shutdown
(desk-changer-daemon.py:21883): -DEBUG: 11:54:19.909: saving state of profile test

(desk-changer-daemon.py:21883): -CRITICAL **: 11:54:19.910: failed to save the state of test: no wallpapers available
Traceback (most recent call last):
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/application.py", line 196, in do_shutdown
    self._desktop_profile.save_state()
  File "/home/jeffshee/.local/share/gnome-shell/extensions/desk-changer@eric.gach.gmail.com/deskchanger/profiles.py", line 306, in save_state
    states[self.name] = (self._background.get_string('picture-uri'), self._queue[0])
IndexError: list index out of range

(desk-changer-daemon.py:21883): GLib-GIO-CRITICAL **: 11:54:19.911: GApplication subclass 'deskchanger+application+Daemon' failed to chain up on ::shutdown (from end of override function)
(desk-changer-daemon.py:21883): -DEBUG: 11:54:19.912: ::dbus_unregister
-INFO: 11:54:19.913: removing DBus registration for name /org/gnome/Shell/Extensions/DeskChanger/Daemon
```

Fedora 28
Gnome 3.28.2

**Comment by BigE** [comment]
Closing with the new rewrite now in develop.
